import {IQuestionsList} from '../types/IQuestionsList';
import {IThemeGrade} from '../types/IThemGrade';
import {IQuestionGrade} from '../types/IQuestionGrade';
import {IQuestionLevel} from '../types/IQuestionLevel';

export const CSSQuestionsList: IQuestionsList = {
    themes: [
        {
            id: '2',
            name: 'CSS',
            grade: IThemeGrade.NONE,
            questions: [
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Specificity',
                    theme: 'Specificity',
                    suggestion: 'Specificity',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: '!important',
                    theme: '!important',
                    suggestion: '!important',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'position',
                    theme: 'position',
                    suggestion: 'position',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'flow',
                    theme: 'flow',
                    suggestion: 'flow',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'position values',
                    theme: 'position values',
                    suggestion: 'position values',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'relative vs absolute',
                    theme: 'relative vs absolute',
                    suggestion: 'relative vs absolute',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'display',
                    theme: 'display',
                    suggestion: 'display',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'display values',
                    theme: 'display values',
                    suggestion: 'display values',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'inline-block behavior',
                    theme: 'inline-block behavior',
                    suggestion: 'inline-block behavior',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'flex-box',
                    theme: 'flex-box',
                    suggestion: 'flex-box',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'flex-box layout',
                    theme: 'flex-box layout',
                    suggestion: 'flex-box layout',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'main and cross axis',
                    theme: 'main and cross axis',
                    suggestion: 'main and cross axis',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'container and elements',
                    theme: 'container and elements',
                    suggestion: 'container and elements',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'container properties',
                    theme: 'container properties',
                    suggestion: 'container properties',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'align-item vs align-content',
                    theme: 'align-item vs align-content',
                    suggestion: 'align-item vs align-content',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'element properties',
                    theme: 'element properties',
                    suggestion: 'flex-box: element properties',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'flex-grow',
                    theme: 'flex-grow',
                    suggestion: 'flex-grow',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'flex-shrink',
                    theme: 'flex-shrink',
                    suggestion: 'flex-shrink',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'flex-basis',
                    theme: 'flex-basis',
                    suggestion: 'flex-basis',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'align-self',
                    theme: 'align-self',
                    suggestion: 'align-self',
                    grade: IQuestionGrade.NONE,
                },
            ]
        }
    ]
};
