import {IQuestionsList} from '../types/IQuestionsList';
import {IThemeGrade} from '../types/IThemGrade';
import {IQuestionGrade} from '../types/IQuestionGrade';
import {IQuestionLevel} from '../types/IQuestionLevel';

export const CSSQuestionsList: IQuestionsList = {
    themes: [
        {
            id: '2',
            name: 'CSS',
            grade: IThemeGrade.NONE,
            questions: [
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Веса селекторов',
                    theme: 'Веса селекторов',
                    suggestion: 'Веса селекторов',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: '!important',
                    theme: '!important',
                    suggestion: '!important',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'position',
                    theme: 'position',
                    suggestion: 'position',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'flow',
                    theme: 'flow',
                    suggestion: 'flow',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'значение свойства position',
                    theme: 'значение свойства position',
                    suggestion: 'значение свойства position',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'relative vs absolute',
                    theme: 'relative vs absolute',
                    suggestion: 'relative vs absolute',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'display',
                    theme: 'display',
                    suggestion: 'display',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'значения свойства display',
                    theme: 'значения свойства display',
                    suggestion: 'значения свойства display',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'поведение inline-block элементов',
                    theme: 'поведение inline-block элементов',
                    suggestion: 'поведение inline-block элементов',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'flex-box',
                    theme: 'flex-box',
                    suggestion: 'flex-box',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'flex-box layout',
                    theme: 'flex-box layout',
                    suggestion: 'flex-box layout',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'основная и поперечная ось',
                    theme: 'основная и поперечная ось',
                    suggestion: 'основная и поперечная ось',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'контейнеры и элементы',
                    theme: 'контейнеры и элементы',
                    suggestion: 'container and elements',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'свойства контейнеров',
                    theme: 'свойства контейнеров',
                    suggestion: 'свойства контейнеров',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'align-item vs align-content',
                    theme: 'align-item vs align-content',
                    suggestion: 'align-item vs align-content',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'свойства элементов',
                    theme: 'свойства элементов',
                    suggestion: 'flex-box: свойства элементов',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'flex-grow',
                    theme: 'flex-grow',
                    suggestion: 'flex-grow',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'flex-shrink',
                    theme: 'flex-shrink',
                    suggestion: 'flex-shrink',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'flex-basis',
                    theme: 'flex-basis',
                    suggestion: 'flex-basis',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'align-self',
                    theme: 'align-self',
                    suggestion: 'align-self',
                    grade: IQuestionGrade.NONE,
                },
            ]
        }
    ]
};
