import {IQuestionsList} from '../types/IQuestionsList';
import {IThemeGrade} from '../types/IThemGrade';
import {IQuestionGrade} from '../types/IQuestionGrade';
import {IQuestionLevel} from '../types/IQuestionLevel';

export const JavaScriptQuestionsList: IQuestionsList = {
    themes: [
        {
            id: '2',
            name: 'JavaScript',
            grade: IThemeGrade.NONE,
            questions: [
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Event-loop',
                    theme: 'Event-loop',
                    suggestion: 'Event-loop',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'структура',
                    theme: 'структура',
                    suggestion: 'Event-loop стурктура',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'micro-task и macro-task',
                    theme: 'micro-task и macro-task',
                    suggestion: 'micro-task и macro-task',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'кэлбэки на пользовательские действия',
                    theme: 'кэлбэки на пользовательские действия',
                    suggestion: 'асинхронность кэлбэков на пользовательские действия',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'ES6+ фичи',
                    theme: 'ES6+ фичи',
                    suggestion: 'ES6+ фичи',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'спрэд оператор',
                    theme: 'спрэд оператор',
                    suggestion: 'спрэд оператор',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'generator',
                    theme: 'generator',
                    suggestion: 'generator (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Generator)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'async/await',
                    theme: 'async/await',
                    suggestion: 'async/await',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'var vs let vs const',
                    theme: 'var vs let vs const',
                    suggestion: 'var vs let vs const',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'область видимости var vs let',
                    theme: 'область видимости var vs let',
                    suggestion: 'область видимости var vs let',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Hoisting',
                    theme: 'Hoisting',
                    suggestion: 'Hoisting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Closure',
                    theme: 'Closure',
                    suggestion: 'Closure',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Типы данных',
                    theme: 'Типы данных',
                    suggestion: 'Типы данных',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'примитивные типы данных vs объекты',
                    theme: 'примитивные типы данных vs объекты',
                    suggestion: 'примитивные типы данных vs объекты',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Symbol',
                    theme: 'Symbol',
                    suggestion: 'Symbol',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'null vs undefined',
                    theme: 'null vs undefined',
                    suggestion: 'null vs undefined',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Обертки примитивных типов данных',
                    theme: 'Обертки примитивных типов данных',
                    suggestion: 'Обертки примитивных типов данных',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'typeOf vs instanceof',
                    theme: 'typeOf vs instanceof',
                    suggestion: 'typeOf vs instanceof',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Object',
                    theme: 'Object',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'object.freeze',
                    theme: 'object.freeze',
                    suggestion: 'object.freeze',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'object.seal',
                    theme: 'object.seal',
                    suggestion: 'object.seal',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Array',
                    theme: 'Array',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Array: map vs forEach',
                    theme: 'Array: map vs forEach',
                    suggestion: 'Array: map vs forEach',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Array vs Map vs Set',
                    theme: 'Array vs Map vs Set',
                    suggestion: 'Array vs Map vs Set',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Function',
                    theme: 'Function',
                    suggestion: 'Function',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'IIFE - Immediately Invoked Function Expression',
                    theme: 'IIFE - Immediately Invoked Function Expression',
                    suggestion: 'IIFE - Immediately Invoked Function Expression',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Arrow function vs Function Expression',
                    theme: 'Arrow function vs Function Expression',
                    suggestion: 'Arrow function vs Function Expression',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Context',
                    theme: 'Context',
                    suggestion: 'Context',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'bind, call, apply',
                    theme: 'bind, call, apply',
                    suggestion: 'bind, call, apply',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'потеря контекста',
                    theme: 'потеря контекста',
                    suggestion: 'потеря контекста',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Promise',
                    theme: 'Promise',
                    suggestion: 'Promise',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Promise.all',
                    theme: 'Promise.all',
                    suggestion: 'Promise.all',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Promise.race',
                    theme: 'Promise.race',
                    suggestion: 'Promise.race',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'fetch',
                    theme: 'fetch',
                    suggestion: 'fetch',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'DOM',
                    theme: 'DOM',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'обработка событий',
                    theme: 'обработка событий',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'addEventListener и onclick',
                    theme: 'addEventListener и onclick',
                    suggestion: 'addEventListener и onclick',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'bubbling vs capturing',
                    theme: 'bubbling vs capturing',
                    suggestion: 'bubbling vs capturing',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: ' e.preventDefault, e.stopPropagation, e.stopImmediatePropagation',
                    theme: ' e.preventDefault, e.stopPropagation, e.stopImmediatePropagation',
                    suggestion: ' e.preventDefault, e.stopPropagation, e.stopImmediatePropagation',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'getElementByClass vs querySelector',
                    theme: 'getElementByClass vs querySelector',
                    suggestion: 'getElementByClass vs querySelector',
                    grade: IQuestionGrade.NONE,
                },
            ]
        }
    ]
};
