import {IQuestionsList} from '../types/IQuestionsList';
import {IThemeGrade} from '../types/IThemGrade';
import {IQuestionGrade} from '../types/IQuestionGrade';
import {IQuestionLevel} from '../types/IQuestionLevel';

export const ReactQuestionsList: IQuestionsList = {
    themes: [
        {
            id: '1',
            name: 'React',
            grade: IThemeGrade.NONE,
            questions: [
                {
                    id: '1.1',
                    level: IQuestionLevel.FIRST,
                    question: 'JSX',
                    theme: 'JSX',
                    grade: IQuestionGrade.NONE,
                    suggestion: '',
                },
                {
                    id: '1.2',
                    level: IQuestionLevel.SECOND,
                    question: 'реализации элемента без jsx',
                    theme: 'реализации элемента без jsx',
                    suggestion: 'реализации элемента без jsx (https://ru.reactjs.org/docs/react-without-jsx.html)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.3',
                    level: IQuestionLevel.THIRD,
                    question: 'React.CreateElement',
                    theme: 'React.CreateElement',
                    suggestion: 'React.CreateElement',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.4',
                    level: IQuestionLevel.SECOND,
                    question: 'React.Fragment',
                    theme: 'React.Fragment',
                    suggestion: 'React.Fragment',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.4',
                    level: IQuestionLevel.THIRD,
                    question: 'React.Fragment vs div',
                    theme: 'React.Fragment vs div',
                    suggestion: 'React.Fragment vs div',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.4',
                    level: IQuestionLevel.FIRST,
                    question: 'Hooks',
                    theme: 'Hooks',
                    grade: IQuestionGrade.NONE,
                    suggestion: '',
                },
                {
                    id: '1.5',
                    level: IQuestionLevel.SECOND,
                    question: 'useEffect',
                    theme: 'useEffect',
                    grade: IQuestionGrade.NONE,
                    suggestion: '',
                },
                {
                    id: '1.6',
                    level: IQuestionLevel.THIRD,
                    question: 'порядок вызова',
                    theme: 'порядок вызова',
                    suggestion: 'порядок вызова useEffect и render (https://dev.to/bytebodger/constructors-in-functional-components-with-hooks-280m)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'массив зависимостей',
                    theme: 'массив зависимостей',
                    suggestion: 'useEffect: массив зависимостей',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'пустой массив зависимостей vs без массива зависимостей',
                    theme: 'пустой массив зависимостей vs без массива зависимостей',
                    suggestion: 'useEffect: пустой массив зависимостей vs без массива зависимостей',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'возвращаемая функция',
                    theme: 'возвращаемая функция',
                    suggestion: 'useEffect: возвращаемая функция',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'вызов возвращаемой функции без массива зависимостей',
                    theme: 'вызов возвращаемой функции без массива зависимостей',
                    suggestion: 'useEffect: вызов возвращаемой функции без массива зависимостей',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'useState',
                    theme: 'useState',
                    suggestion: 'useState',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'значение по умолчанию',
                    theme: 'значение по умолчанию',
                    suggestion: 'useState: значение по умолчанию',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'функция как значение по умолчанию',
                    theme: 'функция как значение по умолчанию',
                    suggestion: 'useState: функция как значение по умолчанию',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'функция в setState',
                    theme: 'функция в setState',
                    suggestion: 'useState: функция в setState',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'useContext',
                    theme: 'useContext',
                    suggestion: 'useContext',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'React.Context',
                    theme: 'React.Context',
                    suggestion: 'React.Context',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'Context.Provider',
                    theme: 'Context.Provider',
                    suggestion: 'Context.Provider',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'Context.Consumer',
                    theme: 'Context.Consumer',
                    suggestion: 'Context.Consumer',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'недостатки использования React.Context',
                    theme: 'недостатки использования React.Context',
                    suggestion: 'недостатки использования React.Context',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'useMemo',
                    theme: 'useMemo',
                    suggestion: 'useMemo',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'патерн мемоизация',
                    theme: 'патерн мемоизация',
                    suggestion: 'патерн мемоизация',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'массив зависимостей',
                    theme: 'массив зависимостей',
                    suggestion: 'useMemo: массив зависимостей',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'useMemo vs useCallback',
                    theme: 'useMemo vs useCallback',
                    suggestion: 'useMemo vs useCallback',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'useMemo vs React.memo',
                    theme: 'useMemo vs React.memo',
                    suggestion: 'useMemo vs React.memo',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'useLayoutEffect',
                    theme: 'useLayoutEffect',
                    suggestion: 'useLayoutEffect',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'порядок вызова',
                    theme: 'порядок вызова',
                    suggestion: 'порядок вызова useLayoutEffect (https://dev.to/bytebodger/constructors-in-functional-components-with-hooks-280m)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'useLayoutEffect vs useEffect',
                    theme: 'useLayoutEffect vs useEffect',
                    suggestion: 'useLayoutEffect vs useEffect (https://daveceddia.com/useeffect-vs-uselayouteffect/)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'useRef',
                    theme: 'useRef',
                    suggestion: 'useRef',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'ref',
                    theme: 'ref',
                    suggestion: 'ref',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'useRef vs useState',
                    theme: 'useRef vs useState',
                    suggestion: 'useRef vs useState',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'правила использования хуков',
                    theme: 'правила использования хуков',
                    suggestion: 'правила использования хуков',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'правила создания кастомных хуков',
                    theme: 'правила создания кастомных хуков',
                    suggestion: 'правила создания кастомных хуков',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'VirtualDOM',
                    theme: 'VirtualDOM',
                    suggestion: 'VirtualDOM',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'алгоритм реконсиляции',
                    theme: 'алгоритм реконсиляции',
                    suggestion: 'алгоритм реконсиляции',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'key',
                    theme: 'key',
                    suggestion: 'key',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: "индекс массива в качестве key",
                    theme: "индекс массива в качестве key",
                    suggestion: "индекс массива в качестве key",
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'использование “реального” DOM iвместо Virtual Dom',
                    theme: 'использование “реального” DOM iвместо Virtual Dom',
                    suggestion: 'использование “реального” DOM iвместо Virtual Dom',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'React.Portal',
                    theme: 'React.Portal',
                    suggestion: 'React.Portal',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'Error Boundary',
                    theme: 'Error Boundary',
                    suggestion: 'Error Boundary',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'try/catch в JSX',
                    theme: 'try/catch в JSX',
                    suggestion: 'try/catch в JSX',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'реализация',
                    theme: 'реализация',
                    suggestion: 'Error Boundary реализация',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'HOC',
                    theme: 'HOC',
                    suggestion: 'HOC',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'Классовые компоненты',
                    theme: 'Классовые компоненты',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'методы жизненного цикла',
                    theme: 'методы жизненного цикла',
                    suggestion: 'методы жизненного цикла классовых компонентов',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'статические методы жизненного цикла',
                    theme: 'статические методы жизненного цикла',
                    suggestion: 'статические методы жизненного цикла классовых компонент',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'PureComponent',
                    theme: 'PureComponent',
                    suggestion: 'PureComponent',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'реализация shouldComponentUpdate',
                    theme: 'реализация shouldComponentUpdate',
                    suggestion: 'реализация shouldComponentUpdate в PureComponent',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'shallowEqual',
                    theme: 'shallowEqual',
                    suggestion: 'shallowEqual',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'Оптимизация react приложения',
                    theme: 'Оптимизация react приложения',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'мемоизация',
                    theme: 'мемоизация',
                    suggestion: 'мемоизация',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'shouldComponentUpdate',
                    theme: 'shouldComponentUpdate',
                    suggestion: 'shouldComponentUpdate',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'пагинация',
                    theme: 'пагинация',
                    suggestion: 'пагинация для улучшения производительности больших списков',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'виртуализация',
                    theme: 'виртуализация',
                    suggestion: 'виртуализация для улучшения производительности больших списков',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'lazy loading',
                    theme: 'lazy loading',
                    suggestion: 'lazy loading для улучшения производительности больших списков',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'Архитектура React приложений',
                    theme: 'Архитектура React приложений',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'умные и глупые компоненты',
                    theme: 'умные и глупые компоненты',
                    suggestion: 'умные и глупые компоненты',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'преимущества и недостатки использования умных и глупых компонент',
                    theme: 'преимущества и недостатки использования умных и глупых компонент',
                    suggestion: 'преимущества и недостатки использования умных и глупых компонент',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.SECOND,
                    question: 'атомный дизайн',
                    theme: 'атомный дизайн',
                    suggestion: 'атомный дизайн',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.THIRD,
                    question: 'преимущества и недостатки использования атомного дизайна',
                    theme: 'преимущества и недостатки использования атомного дизайна',
                    suggestion: 'преимущества и недостатки использования атомного дизайна',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '1.7',
                    level: IQuestionLevel.FIRST,
                    question: 'Преимущества и недостатки использования React',
                    theme: 'Преимущества и недостатки использования React',
                    suggestion: 'Преимущества и недостатки использования React',
                    grade: IQuestionGrade.NONE,
                },
            ],
        },
    ]
};
