import {IQuestionsList} from '../types/IQuestionsList';
import {IThemeGrade} from '../types/IThemGrade';
import {IQuestionLevel} from '../types/IQuestionLevel';
import {IQuestionGrade} from '../types/IQuestionGrade';

export const SoftSkillsQuestionList: IQuestionsList = {
    themes: [
        {
            id: '2',
            name: 'Процессы/качество кода/софт скиллы',
            grade: IThemeGrade.NONE,
            questions: [
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'CI/CD',
                    theme: 'CI/CD',
                    suggestion: 'CI/CD (https://www.atlassian.com/continuous-delivery)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'пайплайн проекта',
                    theme: 'пайплайн проекта',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'CI шаги',
                    theme: 'CI шаги',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'CI vs CD',
                    theme: 'CI vs CD',
                    suggestion: 'CI vs CD (https://www.atlassian.com/ru/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'настройка CI/CD',
                    theme: 'настройка CI/CD',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Стратегии бранчинга',
                    theme: 'Стратегии бранчинга',
                    suggestion: 'Стратегии бранчинга (https://www.toptal.com/software/trunk-based-development-git-flow)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Git flow',
                    theme: 'Git flow',
                    suggestion: 'Git flow',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Trunk based ',
                    theme: 'Trunk based ',
                    suggestion: 'Trunk based (https://trunkbaseddevelopment.com/)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Code review',
                    theme: 'Code review',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'достоинства и недостатки code review',
                    theme: 'достоинства и недостатки code review',
                    suggestion: 'достоинства и недостатки code review',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Качество кода',
                    theme: 'Качество кода',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'базовые принципы качества кода (наименование, переиспользование)',
                    theme: 'базовые принципы качества кода (наименование, переиспользование)',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'SOLID',
                    theme: 'SOLID',
                    suggestion: 'SOLID',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'single responsibility',
                    theme: 'single responsibility',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'open-closed',
                    theme: 'open-closed',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'dependency inversion',
                    theme: 'dependency inversion',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'YAGNI',
                    theme: 'YAGNI',
                    suggestion: 'YAGNI',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'DRY',
                    theme: 'DRY',
                    suggestion: 'DRY',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'KISS',
                    theme: 'KISS',
                    suggestion: 'KISS',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'SCRUM',
                    theme: 'SCRUM',
                    suggestion: 'SCRUM (https://www.atlassian.com/ru/agile/scrum)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'роли',
                    theme: 'роли',
                    suggestion: 'SCRUM: роли (https://www.atlassian.com/ru/agile/scrum/roles)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Scrum master',
                    theme: 'Scrum master',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Product owner',
                    theme: 'Product owner',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'митинги',
                    theme: 'митинги',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'planning',
                    theme: 'planning',
                    suggestion: 'SCRUM: planning meeting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'daily',
                    theme: 'daily',
                    suggestion: 'SCRUM: daily meeting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'retrospective',
                    theme: 'retrospective',
                    suggestion: 'SCRUM: retrospective meeting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'sprint',
                    theme: 'sprint',
                    suggestion: 'SCRUM: sprint',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Agile',
                    theme: 'Agile',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'принципы',
                    theme: 'принципы',
                    suggestion: 'Agile принципы (https://www.atlassian.com/ru/agile/manifesto)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'KANBAN vs SCRUM',
                    theme: 'KANBAN vs SCRUM',
                    suggestion: 'KANBAN vs SCRUM (https://www.atlassian.com/ru/agile/kanban/kanban-vs-scrum)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Waterfall vs SCRUM',
                    theme: 'Waterfall vs SCRUM',
                    suggestion: 'Waterfall vs SCRUM',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Оценка задач',
                    theme: 'Оценка задач',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'в часах, использование своего опыта',
                    theme: 'в часах, использование своего опыта',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'техники',
                    theme: 'техники',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Planning Poker',
                    theme: 'Planning Poker',
                    suggestion: 'Planning Poker',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'StoryPoint',
                    theme: 'StoryPoint',
                    suggestion: 'StoryPoint (https://habr.com/ru/post/489500/)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Story Points vs часы',
                    theme: 'Story Points vs часы',
                    suggestion: 'Story Points vs часы',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Unit Testing',
                    theme: 'Unit Testing',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'достоинства и недостатки',
                    theme: 'достоинства и недостатки',
                    suggestion: 'достоинства и недостатки unit testing',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'FIRST',
                    theme: 'FIRST',
                    suggestion: 'FIRST принцип юнит тестирования',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'AAA',
                    theme: 'AAA',
                    suggestion: 'AAA принцип юнит тестирования',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'TDD',
                    theme: 'TDD',
                    suggestion: 'TDD методология',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Достоинства и недостатки парного программирования',
                    theme: 'Достоинства и недостатки парного программирования',
                    suggestion: 'Достоинства и недостатки парного программирования',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Ведение проекта с чистого листа',
                    theme: 'Ведение проекта с чистого листа',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Выбор технологий',
                    theme: 'Выбор технологий',
                    suggestion: 'Выбор технологий для проекта с чистого листа',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Выбор и настройка процессов',
                    theme: 'Выбор и настройка процессов',
                    suggestion: 'Выбор и настройка процессов для проекта с чистого листа',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Решение конфликтов',
                    theme: 'Решение конфликтов',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Key developer/Team Lead роли',
                    theme: 'Key developer/Team Lead роли',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Аргументация решений для заказчика и коллег',
                    theme: 'Аргументация решений для заказчика и коллег',
                    suggestion: 'Аргументация решений для заказчика и коллег',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Общение с заказчиком по поводу дедлайнов',
                    theme: 'Общение с заказчиком по поводу дедлайнов',
                    suggestion: 'Общение с заказчиком по поводу дедлайнов',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Делегирование',
                    theme: 'Делегирование',
                    suggestion: 'Делегирование',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'time-management',
                    theme: 'time-management',
                    suggestion: 'time-management',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'pomodoro technique',
                    theme: 'pomodoro technique',
                    suggestion: 'pomodoro technique',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Eisenhower Matrix',
                    theme: 'Eisenhower Matrix',
                    suggestion: 'Eisenhower Matrix',
                    grade: IQuestionGrade.NONE,
                },
            ]
        }
    ]
}