import {IQuestionsList} from "../types/IQuestionsList";
import {IThemeGrade} from "../types/IThemGrade";
import {IQuestionLevel} from "../types/IQuestionLevel";
import {IQuestionGrade} from "../types/IQuestionGrade";

export const SoftSkillsQuestionList: IQuestionsList = {
    themes: [
        {
            id: '2',
            name: 'Processes/code quality/soft-skills',
            grade: IThemeGrade.NONE,
            questions: [
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'CI/CD',
                    theme: 'CI/CD',
                    suggestion: 'CI/CD (https://www.atlassian.com/continuous-delivery)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'project’s pipeline',
                    theme: 'project’s pipeline',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'CI steps',
                    theme: 'CI steps',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'CI vs CD',
                    theme: 'CI vs CD',
                    suggestion: 'CI vs CD (https://www.atlassian.com/ru/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'setup CI/CD environment',
                    theme: 'setup CI/CD environment',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Branching strategy',
                    theme: 'Branching strategy',
                    suggestion: 'Branching strategy (https://www.toptal.com/software/trunk-based-development-git-flow)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Git flow',
                    theme: 'Git flow',
                    suggestion: 'Git flow',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Trunk based ',
                    theme: 'Trunk based ',
                    suggestion: 'Trunk based (https://trunkbaseddevelopment.com/)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Code review',
                    theme: 'Code review',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'advantages, disadvantages of code review',
                    theme: 'advantages, disadvantages of code review',
                    suggestion: 'advantages, disadvantages of code review',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'cross-check',
                    theme: 'cross-check',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Code quality',
                    theme: 'Code quality',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'base principles (naming, reusing code)',
                    theme: 'base principles (naming, reusing code)',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'SOLID',
                    theme: 'SOLID',
                    suggestion: 'SOLID',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'single responsibility',
                    theme: 'single responsibility',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'open-closed',
                    theme: 'open-closed',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'dependency inversion',
                    theme: 'dependency inversion',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'YAGNI',
                    theme: 'YAGNI',
                    suggestion: 'YAGNI',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'DRY',
                    theme: 'DRY',
                    suggestion: 'DRY',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'KISS',
                    theme: 'KISS',
                    suggestion: 'KISS',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'SCRUM',
                    theme: 'SCRUM',
                    suggestion: 'SCRUM (https://www.atlassian.com/ru/agile/scrum)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'roles',
                    theme: 'roles',
                    suggestion: 'roles (https://www.atlassian.com/ru/agile/scrum/roles)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Scrum master',
                    theme: 'Scrum master',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Product owner',
                    theme: 'Product owner',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'meetings',
                    theme: 'meetings',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'planning',
                    theme: 'planning',
                    suggestion: 'SCRUM: planning meeting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'daily',
                    theme: 'daily',
                    suggestion: 'SCRUM: daily meeting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'retrospective',
                    theme: 'retrospective',
                    suggestion: 'SCRUM: retrospective meeting',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'sprint',
                    theme: 'sprint',
                    suggestion: 'SCRUM: sprint',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Agile',
                    theme: 'Agile',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'principles',
                    theme: 'principles',
                    suggestion: 'Agile principles (https://www.atlassian.com/ru/agile/manifesto)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'KANBAN vs SCRUM',
                    theme: 'KANBAN vs SCRUM',
                    suggestion: 'KANBAN vs SCRUM (https://www.atlassian.com/ru/agile/kanban/kanban-vs-scrum)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Waterfall vs SCRUM',
                    theme: 'Waterfall vs SCRUM',
                    suggestion: 'Waterfall vs SCRUM',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Task estimation',
                    theme: 'Task estimation',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'hours, using self-experience',
                    theme: 'hours, using self-experience',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'techniques',
                    theme: 'techniques',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Planning Poker',
                    theme: 'Planning Poker',
                    suggestion: 'Planning Poker',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'StoryPoint',
                    theme: 'StoryPoint',
                    suggestion: 'StoryPoint (https://habr.com/ru/post/489500/)',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.THIRD,
                    question: 'Story Points vs hours',
                    theme: 'Story Points vs hours',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Unit Testing',
                    theme: 'Unit Testing',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'advantages and disadvantages',
                    theme: 'advantages and disadvantages',
                    suggestion: 'advantages and disadvantages of unit testing',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'FIRST',
                    theme: 'FIRST',
                    suggestion: 'FIRST principle of unit testing',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'AAA',
                    theme: 'AAA',
                    suggestion: 'AAA principle of unit testing',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'TDD',
                    theme: 'TDD',
                    suggestion: 'TDD methodology',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Advantages and disadvantages pair programming',
                    theme: 'Advantages and disadvantages pair programming',
                    suggestion: 'Advantages and disadvantages pair programming',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Advantages and disadvantages pair programming',
                    theme: 'Advantages and disadvantages pair programming',
                    suggestion: 'Advantages and disadvantages pair programming',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Project from scratch',
                    theme: 'Project from scratch',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'choosing technologies',
                    theme: 'choosing technologies',
                    suggestion: 'choosing technologies for project from scratch',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'choosing methodologies of processes',
                    theme: 'choosing methodologies of processes',
                    suggestion: 'choosing methodologies of processes for project from scratch',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Conflict solving',
                    theme: 'Conflict solving',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Key developer/Team leader roles',
                    theme: 'Key developer/Team leader roles',
                    suggestion: '',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Argumentation of solution for Customer and Colleagues',
                    theme: 'Argumentation of solution for Customer and Colleagues',
                    suggestion: 'Argumentation of solution for Customer and Colleagues',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Talking about deadlines with customer',
                    theme: 'Talking about deadlines with customer',
                    suggestion: 'Talking about deadlines with customer',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'Delegation',
                    theme: 'Delegation',
                    suggestion: 'Delegation',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.FIRST,
                    question: 'time-management',
                    theme: 'time-management',
                    suggestion: 'time-management',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'pomodoro technique',
                    theme: 'pomodoro technique',
                    suggestion: 'pomodoro technique',
                    grade: IQuestionGrade.NONE,
                },
                {
                    id: '2.1',
                    level: IQuestionLevel.SECOND,
                    question: 'Eisenhower Matrix',
                    theme: 'Eisenhower Matrix',
                    suggestion: 'Eisenhower Matrix',
                    grade: IQuestionGrade.NONE,
                },
            ]
        }
    ]
}